### ISSUE TITLE
Error: stdClass Object

### ISSUE THREAD

**Issue by habibulilalbaab** [Elompenta/hashnest-php-api#1]
Error: stdClass Object ( [error] => stdClass Object ( [code] => 2001 [message] => Authorization failed ) ) 

Please help

**Comment by Elompenta** [comment]
Do you have any more informations?
Can you Show your Code? (please remove your API Keys)

**Comment by habibulilalbaab** [comment]
I'm use demo file from github

**Comment by Elompenta** [comment]
@LJKMGroups 
I have tested the demo file with the current github Version.

You are right - the authorization doesnt work anymore, but the code seems correct :/
I've found some other people they have also trouble to login via API.
I have opened a hashnest Ticket (#7526) to check there API-authorization process.

I will let you know if i have recieved Feedback.

Greetz

**Comment by habibulilalbaab** [comment]
Okay,, thanks i will waiting for it
31 Jul 2017 01.51, "Sebastian" <notifications@github.com> menulis:

**Comment by Elompenta** [comment]
@LJKMGroups 
I have updated the documentation - The Username cannot be your Account Email.
Now the current Github Version works fine!

Please test it again.
If you still have Problems, create a new API Key WITHOUT access to your balance or trades and ping me by email.
